title: Sane's blog
tagline: Various physics things from S. S. Sane
description: Sane's website, covering various projects in physics since 2018
markdown: kramdown
kramdown:
  math_engine: katex
plugins:
- jekyll-remote-theme
